name: test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    container: golangci/golangci-lint
    steps:
    - uses: actions/checkout@v2
    - run: golangci-lint run ./...

  tfproviderlint:
    runs-on: ubuntu-latest
    container: bflad/tfproviderlint
    steps:
    - uses: actions/checkout@v2
    - run: tfproviderlint ./...

  go-test:
    runs-on: ubuntu-latest
    env:
      TF_ACC: 1
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '~1.14'
    - run: go test -v ./...
